### ISSUE TITLE
Feature Request: Monitor specific devices via IP -or- DNS name

### ISSUE THREAD

**Issue by QueenLinuxGlitch** [gabe565/CastSponsorSkip#8]
What if instead of monitoring the entire subnet for casting devices, one possible command-line option could be something like '--device-list' with a string list like '192.168.0.3','10.0.0.5' -or- cast1.contoso.local,cast2.fabrikam.local

Case being, not even a huge issue, but I have 4 cast devices in my office, two speakers, two chromecasts. I just don't care if it monitors the speakers, and if there are a large amount of cast devices in a discoverable network, then it may be more prudent resource-wise to allow the 'Selection' of devices.

I'm wondering if focusing on one device would allow sponsorskips, e.g. to be detected quicker, and executed quicker, based on not having to poll unnecessary devices

**Comment by gabe565** [comment]
I think this is a good idea, but it's a little bit lower on my radar. The service is already pretty light and I haven't had any issues with high CPU or delayed skips, even though I have 12 Cast devices (I promise I got some of these for free...). Have you had any issues yet?

Lower CPU and quick response time is mainly due to the fact that CastSponsorSkip only polls devices once per second if a device is playing a YouTube video, otherwise it slows that interval to once per minute.

Would it make more sense if it could filter out the speakers? Then, static IP configuration wouldn't be necessary, and unnecessary polls would still be eliminated. I have an approach that I'm testing, but I'm not sure if it will be reliable on all Cast devices yet.

**Comment by gabe565** [comment]
Hmm although I just realized a benefit of adding a `--devices` flag. Not all deployment strategies will be able to discover devices within the LAN (namely, some containerized environments). Hard coding a device list would be a nice fallback for people who can't get DNS discovery working.

**Comment by QueenLinuxGlitch** [comment]
I'm not using containers for this, but I can see the application in that case. 

For me, sometimes when the moon is high, a few seconds of a sponsor may get through, or the detection may come in too late to get content close to the beginning of the video. 

Currently getting an Ethernet adapter for my Chromecast to see if any difference is made, also because why not

**Comment by gabe565** [comment]
Try the latest version! The app automatically ignores speakers now and will only watch the status of video devices. Should help.

I wouldn't recommend lowering the pause scan interval if possible. Devices send a notification when a video starts, so the pause poll is mainly to detect if the device is still connected.

**Comment by QueenLinuxGlitch** [comment]
Just downloaded the newest version, I'm going to install my Ethernet adapter and test to see if everything works better, but i consider this closed.

I appreciate selecting only Video devices! May need to implement an optional listen to speakers incase of listening to youtube videos, but I personally do not have that use case. Cheers, dude :)

**Comment by QueenLinuxGlitch** [comment]
#11
